apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-service-account
  namespace: jenkins
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::253823388836:role/eks_admin_role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: agent-service-account
    namespace: jenkins
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io